### ISSUE TITLE
Build won't run

### ISSUE THREAD

**Issue by ouyangal** [BYK/superset#3]
Error Message: Failed at superset@0.18.5 build script  'NODE_ENV=production webpack --colors --progress'.

Node and npm are all updated.

**Comment by BYK** [comment]
>Failed at superset@0.18.5

Superset never had this release number. Are you sure you are looking at the correct package?

>Node and npm are all updated.

Version numbers would be appreciated to make sure we are talking about the same major versions.

**Comment by ouyangal** [comment]
This is the non-released version because I want to utilize the chord visualization and my custom built visualization.

npm v3.5.2
node v4.2.6

**Comment by BYK** [comment]
@ouyangal I don't think we are talking about the same package then. I am the author of this package and I have never had an "unreleased 0.18.5" version of this package :)

Sorry I couldn't help.
